import Head from 'next/head'
import Comp1 from "../components/comp1"
import Navbar from "../components/navbar"
import Hero from "../components/hero"


export default function Home() {
  return (
    <>
      <Head>
        <title>Word2Vec</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">

        <Navbar />
        <Hero />


        <div className="w-[90%] flex flex-col gap-6 justify-center">
          <h2 className="text-4xl font-bold text-center">Models</h2>
          <div className="grid lg:grid-cols-2 grid-cols-1 gap-8">
            <Comp1 />
            <Comp1 />
            <Comp1 />
            <Comp1 />
          </div>
        </div>
      </main>
    </>
  )
}
